- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/connectors/CGTPropertyDisposalsConnector.scala
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/HomeController.scala
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/email/EmailController.scala
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/email/RegistrationChangeEmailController.scala
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/email/RegistrationEnterEmailController.scala
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/email/SubscribedChangeEmailController.scala
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/email/SubscriptionChangeEmailController.scala
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/email/SubscriptionEnterEmailController.scala
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/http/HttpClient.scala
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/services/SubscriptionService.scala
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/account/manage_your_details.scala.html
- conf/app.routes
- test/uk/gov/hmrc/cgtpropertydisposalsfrontend/connectors/CGTPropertyDisposalsConnectorImplSpec.scala
- test/uk/gov/hmrc/cgtpropertydisposalsfrontend/connectors/HttpSupport.scala
- test/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/email/EmailControllerSpec.scala
- test/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/email/RegistrationChangeEmailControllerSpec.scala
- test/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/email/RegistrationEnterEmailControllerSpec.scala
- test/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/email/SubscribedChangeEmailControllerSpec.scala
- test/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/email/SubscriptionChangeEmailControllerSpec.scala
- test/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/email/SubscriptionEnterEmailControllerSpec.scala
- test/uk/gov/hmrc/cgtpropertydisposalsfrontend/services/SubscriptionServiceImplSpec.scala
@AndyHWChung please could you review these early draft PRs. If you agree with the approach then I will proceed with the tests.
> CPDP-793: amend email

- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/agents/AgentAccessController.scala
- test/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/agents/AgentAccessControllerSpec.scala
> cpdp-1152: unsuccssful verifier match count is not increased when same value is submitted

- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/acquisitiondetails/summary.scala.html
- test/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/returns/acquisitiondetails/AcquisitionDetailsControllerSpec.scala
Made a mistake with the last one. This question was meant for the acquisition price, not the date
> Acquisition price cya rename

- conf/application.conf
- conf/messages
This reverts commit 451fb646c7e776bcf155146ec354efdd44763366.
> Revert "cpdp-1532: temporarily set file upload expiry to 1 day (#437)"

- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/accounts/homepage/HomePageController.scala
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/triage/further_retuns_help.scala.html
- test/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/accounts/homepage/HomePageControllerSpec.scala
Page improvements as well as trust's scenario included
> CPDP-2274 route trusts from start new return to further return help page

- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/returns/yeartodatelliability/YearToDateLiabilityController.scala
Do not unset tax due when updating the the estimate on a further return
> do not unset tax due

- conf/messages
I assume it's as simple as this - no description in the JIRA ticket.
> CPDP-2797: fix H2

- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/returns/amend/AmendReturnController.scala
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/amend/unmet_dependency.scala.html
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/amend/you_need_to_calculate.scala.html
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/exemptionandlosses/further_return_in_year_losses.scala.html
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/exemptionandlosses/in_year_losses.scala.html
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/triage/disposaldate_in_different_taxyear.scala.html
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/ytdliability/year_to_date_liability.scala.html
- conf/messages
- test/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/returns/amend/AmendReturnControllerSpec.scala
- test/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/returns/exemptionandlosses/ExemptionAndLossesControllerSpec.scala
- test/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/returns/yeartodatelliability/YearToDateLiabilityControllerSpec.scala
@AndyHWChung can you have a look at this draft PR as I have changed critical files. If all ok, then I will fix the tests. I don't want to alter the tests specs on a false basis.
> CPDP-2842: content changes for amends

- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/address/disposal_date.scala.html
- test/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/returns/address/MultipleDisposalsPropertyDetailsControllerSpec.scala
> DLS-3942-defect Fixed UI test defect

- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/returns/triage/MultipleDisposalsTriageController.scala
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/models/returns/MultipleDisposalsTriageAnswers.scala
- test/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/returns/triage/MultipleDisposalsTriageControllerSpec.scala
- test/uk/gov/hmrc/cgtpropertydisposalsfrontend/models/returns/MultipleDisposalsTriageAnswersSpec.scala
> DLS-4041 Backwards Compatibility

- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/returns/amend/AmendReturnController.scala
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/returns/triage/CommonTriageQuestionsController.scala
- conf/application.conf
> DLS-3955-1 SA Question - Amendments

- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/triage/exchangedate_incompatible_taxyears.scala.html
- conf/messages
- conf/messages.cy
> DLS-4062 Welsh Translation messages

- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/account/home.scala.html
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/landing_page.scala.html
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/return_saved.scala.html
- conf/messages
Temporary Incorrect Calculation Error Message
> DCWL-118 Temporary Incorrect Calculation Error Message

- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/account/home.scala.html
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/landing_page.scala.html
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/return_saved.scala.html
- conf/messages
Remove warning message from landing page
> DLS-4320 Remove warning message from landing page

- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/Layout.scala.html
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/accessibility_statement.scala.html
- conf/application.conf
- conf/messages
- conf/messages.cy
- public/javascript/session-timeout.js
- updated 'will audit by' date to a concrete date
- updated WCAG level from AAA to AA
- updated content of legal sections and urls to match latest template
- prevented service timeout from firing on statement page
- added statement link to footer of updated pages
> DLS-5356 Updated accessibility statement

- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/address/enter_nonUk_address.scala.html
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/address/enter_uk_address.scala.html
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/components/file_input.scala.html
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/components/radio_group_govuk.scala.html
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/components/text_input_govuk.scala.html
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/components/unit_input.scala.html
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/components/unit_input_govuk.scala.html
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/disposaldetails/disposal_fees.scala.html
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/disposaldetails/disposal_price.scala.html
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/supportingevidence/upload.scala.html
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/triage/how_many_properties.scala.html
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/triage/multipledisposals/how_many_properties.scala.html
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/ytdliability/upload_mandatory_evidence.scala.html
- test/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/returns/address/CompanyDetailsControllerSpec.scala
- test/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/returns/address/MixedUsePropertyDetailsControllerSpec.scala
See related UI tests PR https://github.com/hmrc/cgt-property-disposals-ui-tests/pull/191
> DLS-6213 Misc HTML fixes

- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/returns/triage/MultipleDisposalsTriageController.scala
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/components/new_text_input_govuk.scala.html
- build.sbt
- conf/messages
- conf/messages.cy
- project/AppDependencies.scala
Added new message file entry and validation rules for 2023/2024 tax year
> DLS-6922: new tax year rates

- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/onboarding/change_gg_account.scala.html
- test/uk/gov/hmrc/cgtpropertydisposalsfrontend/services/returns/ReturnsServiceImplSpec.scala
Upgrade the 'Change GG Account' Page to use the new layout and govuk stndards
https://jira.tools.tax.service.gov.uk/browse/DLS-7424
> DLS-7424 CGT [Onboarding]: Upgrade the 'Change GG Account' Page

- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/error_template.scala.html
Upgrade the 'Error Template' Page to new layout
https://jira.tools.tax.service.gov.uk/browse/DLS-7273
> DLS-7273 Upgrade the 'Error Template' Page

- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/triage/multipledisposals/asset_type_for_non_uk_residents.scala.html
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/triage/multipledisposals/completion_date.scala.html
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/triage/multipledisposals/tax_year_exchanged.scala.html
- conf/messages
- conf/messages.cy
https://jira.tools.tax.service.gov.uk/browse/DLS-8057
completion_date: added error field to form error
minor fix for asset type
> DLS-8057 Update error on completion date, minor fix for asset type

- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/representee/name_match_error.scala.html
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/representee/too_many_name_match_failures.scala.html
https://jira.tools.tax.service.gov.uk/browse/DLS-8039
> DLS-8039 update to new layout

- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/representee/change_contact_name.scala.html
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/representee/enter_date_of_death.scala.html
https://jira.tools.tax.service.gov.uk/browse/DLS-8040
Updating to new layout
> DLS-8040 CGT [returns/representee] Upgrade Question Pages

- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/acquisitiondetails/acquisition_fees.scala.html
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/acquisitiondetails/acquisition_price.scala.html
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/acquisitiondetails/improvement_costs.scala.html
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/acquisitiondetails/period_of_admin_market_value.scala.html
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/acquisitiondetails/rebased_acquisition_price.scala.html
- conf/messages
- conf/messages.cy
- test/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/returns/acquisitiondetails/AcquisitionDetailsControllerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/DLS-8131
> DLS-8131 [CGT][returns/acquisitiondetails] Upgrade money pages

- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/returns/supportingevidence/SupportingEvidenceController.scala
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/components/cya_delete_govuk.scala.html
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/supportingevidence/check_your_answers.scala.html
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/supportingevidence/do_you_want_to_upload.scala.html
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/supportingevidence/summary_govuk.scala.html
https://jira.tools.tax.service.gov.uk/browse/DLS-7598
Updating to new layout
> DLS-7598 CGT [returns/supportingevidence]: Upgrade CYA and Question

- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/ytdliability/estimated_income.scala.html
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/ytdliability/has_estimated_details.scala.html
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/ytdliability/personal_allowance.scala.html
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/ytdliability/repayment.scala.html
- conf/messages
- conf/messages.cy
- test/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/returns/yeartodatelliability/YearToDateLiabilityControllerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/DLS-7672
> DLS-7672 CGT [returns/ytdliability]: Upgrade the Question Pages

- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/testonly/JourneyStatusController.scala
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/testonly/set_return_state.scala.html
https://jira.tools.tax.service.gov.uk/browse/DLS-8220
> DLS-8220  CGT - [testonly/] Upgrade set return state page 

- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/AddressController.scala
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/EmailController.scala
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/StartController.scala
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/accounts/homepage/HomePageController.scala
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/actions/AuthenticatedActionWithRetrievedData.scala
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/actions/SubscriptionReadyAction.scala
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/agents/AgentAccessController.scala
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/onboarding/DeterminingIfOrganisationIsTrustController.scala
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/onboarding/InsufficientConfidenceLevelController.scala
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/onboarding/RegistrationController.scala
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/onboarding/SubscriptionController.scala
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/returns/CheckAllAnswersAndSubmitController.scala
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/returns/ViewReturnController.scala
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/returns/supportingevidence/SupportingEvidenceController.scala
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/returns/yeartodatelliability/YearToDateLiabilityController.scala
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/services/onboarding/SubscriptionService.scala
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/services/returns/ReturnsService.scala
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/util/HttpResponseOps.scala
- test/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/EmailControllerSpec.scala
- test/uk/gov/hmrc/cgtpropertydisposalsfrontend/models/returns/CalculatedGlarBreakdownSpec.scala
This service doesn't log any PII, though I thought it would be a good opportunity to rework some of the error handling, which tends to be pretty ugly and makes it difficult to diagnose what is and isn't logged.
> DLS-6750 Refactor error handling

- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/services/returns/ReturnsService.scala
- test/uk/gov/hmrc/cgtpropertydisposalsfrontend/models/returns/CalculatedGlarBreakdownSpec.scala
- test/uk/gov/hmrc/cgtpropertydisposalsfrontend/services/returns/ReturnsServiceImplSpec.scala
[Ticket](https://jira.tools.tax.service.gov.uk/browse/DLS-8772)
> DLS-8772 Returns summary list since 2020 April 06

- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/StartController.scala
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/returns/CheckAllAnswersAndSubmitController.scala
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/models/JourneyStatus.scala
- build.sbt
- project/plugins.sbt
- test/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/onboarding/RedirectToStartBehaviour.scala
- test/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/onboarding/StartControllerSpec.scala
- test/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/returns/CheckAllAnswersAndSubmitControllerSpec.scala
Reverts hmrc/cgt-property-disposals-frontend#1250
> Revert "DLS-9277 - preventing duplicate returns"

- conf/application.conf
- conf/messages
- conf/messages.cy
- reorganised messages to match messages.cy for readability, searchability etc
- both files now have the same structure
- possibly unused entries are at the end
- other than possibly unused entries, both files have same number of lines, all key positions match
> DLS-9283: Reorganised messages.cy

- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/ytdliability/taxable_gain_or_loss.scala.html
- conf/messages
- conf/messages.cy
- test/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/returns/yeartodatelliability/YearToDateLiabilityControllerSpec.scala
[Ticket](https://jira.tools.tax.service.gov.uk/browse/DLS-9284)
> DLS-9284 Update Multiple Gain or Loss page

- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/address/disposal_price.scala.html
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/address/multiple_disposals_summary_govuk.scala.html
- conf/messages
- conf/messages.cy
- changed the page title content for H1 for both Welsh and English
- implemented the 'label' label
- added id to fix failing UI test
- changed structure of the html file
- updated messages files
> DLS-9282 Content changes update

- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/returns/address/PropertyDetailsController.scala
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/returns/triage/MultipleDisposalsTriageController.scala
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/address/multiple_disposals_check_your_answers.scala.html
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/triage/multipledisposals/check_you_answers.scala.html
- conf/messages
- conf/messages.cy
- test/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/returns/address/MultipleDisposalsPropertyDetailsControllerSpec.scala
- test/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/returns/triage/MultipleDisposalsTriageControllerSpec.scala
[Ticket](https://jira.tools.tax.service.gov.uk/browse/DLS-9280)
> DLS-9280 Multiple Disposals Triage CYA Updates

- conf/messages
- conf/messages.cy
[DLS-9243](https://jira.tools.tax.service.gov.uk/browse/DLS-9243)
> DLS-9243 - updated links by adding govuk-link class

- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/address/multiple_disposals_guidance.scala.html
- conf/messages
- conf/messages.cy
- test/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/returns/address/MultipleDisposalsPropertyDetailsControllerSpec.scala
Updated content for different representative user types on multiple disposal guidance page. Screenshots are attached to JIRA ticket https://jira.tools.tax.service.gov.uk/browse/DLS-9281. Thanks
> DLS-9281 | Update multiple disposal journey guidance content

- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/onboarding/already_subscribed_with_different_gg_account.scala.html
- conf/messages
- conf/messages.cy
- corrected heading for already_subscribed_with_different_gg_account.scala.html
- added content changes in Welsh
- added content changes in English
> DLS-9802: Delivery of content changes

- test/uk/gov/hmrc/cgtpropertydisposalsfrontend/connectors/returns/PaymentsConnectorImplSpec.scala
- test/uk/gov/hmrc/cgtpropertydisposalsfrontend/util/WireMockMethods.scala
[CGT] FE Port PaymentsConnector tests to Wiremock
> DLS-10794 wiremock update

- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/config/ViewConfig.scala
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/triage/disposal_date_too_early_uk_residents.scala.html
- app/uk/gov/hmrc/cgtpropertydisposalsfrontend/views/returns/triage/uk_resident_can_only_dispose_residential.scala.html
- conf/application.conf
- conf/messages
- conf/messages.cy
- test/uk/gov/hmrc/cgtpropertydisposalsfrontend/controllers/returns/triage/CommonTriageQuestionsControllerSpec.scala
Implemented new content for 'You cannot use this service' page and updated the link.
> DLS-11523 : Content change

- conf/application.conf
- project/AppDependencies.scala
- we can not write new AT as new and old url is government gateway password protected and we are using production url in all environments.
- Old and New url does not impact our journey and mainly used and managed by different team.
> DLS-11880 [CGTPD-FE] Update agent authorisation handoff link
